plugins {
    id 'com.android.application'
}

android {
    namespace 'com.talkbacklab.focushelper'
    compileSdk 36

    defaultConfig {
        applicationId "com.talkbacklab.focushelper"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint { checkReleaseBuilds = false }
}

dependencies {
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.6.2'
}
